# Generated by Django 6.0.2 on 2026-04-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('benchmark_mode', models.CharField(choices=[('full', 'Full Dataset'), ('subset20', '20 Image Subset'), ('uploaded', 'Uploaded Images')], default='full', max_length=50)),
                ('selected_algorithms', models.JSONField(default=list)),
                ('selected_categories', models.JSONField(default=list)),
                ('parameters', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('relative_path', models.CharField(max_length=500)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_id', models.CharField(max_length=100)),
                ('algorithm_type', models.CharField(blank=True, default='', max_length=50)),
                ('is_patch_based', models.BooleanField(default=False)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('silhouette_score', models.FloatField(blank=True, null=True)),
                ('davies_bouldin_score', models.FloatField(blank=True, null=True)),
                ('inertia', models.FloatField(blank=True, null=True)),
                ('calinski_harabasz_score', models.FloatField(blank=True, null=True)),
                ('dunn_index', models.FloatField(blank=True, null=True)),
                ('fastest_for_image', models.BooleanField(default=False)),
                ('parameters_used', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.benchmarksession')),
                ('dataset_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_results', to='api.datasetimage')),
            ],
        ),
        migrations.CreateModel(
            name='UserStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('benchmark_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_studies', to='api.benchmarksession')),
            ],
        ),
        migrations.CreateModel(
            name='UserImageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=100)),
                ('quality_score', models.IntegerField()),
                ('naturalness_score', models.IntegerField(blank=True, null=True)),
                ('separation_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('benchmark_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.benchmarkresult')),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.userstudysession')),
            ],
        ),
    ]
