# Generated by Django 6.0.2 on 2026-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkresult',
            name='original_image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='benchmarkresult',
            name='result_image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
